server:
#    port: 8080
    context-path: /ControlHoras


security:
  oauth2:
    client:
      clientId: .apps.googleusercontent.com
      clientSecret:  
      accessTokenUri: https://www.googleapis.com/oauth2/v4/token
      userAuthorizationUri: https://accounts.google.com/o/oauth2/v2/auth
      clientAuthenticationScheme: form
      scope: email
    resource:
      userInfoUri: https://www.googleapis.com/oauth2/v3/userinfo
      preferTokenInfo: true


